### ISSUE TITLE
字节跳动Flutter组有兴趣么

### ISSUE THREAD

**Issue by Sunbreak** [daviyang35/NulsWalletSwift#1]
看到你在维护duilib

有兴趣来Flutter组做PC开发么

微信：wk2311007
邮箱：wangkun.sunbreak@bytedance.com

**Comment by daviyang35** [comment]
Package啥水平？

**Comment by Sunbreak** [comment]
> Package啥水平？

一般比BAT高20%，方便加微信说么：wk2311007
